### ISSUE TITLE
CUDA_ERROR_NOT_INITIALIZED

### ISSUE THREAD

**Issue by andrewtsuei** [yuanyuanli85/Keras-Multiple-Process-Prediction#2]
I follow the code and implement my own. When I call keras.models.load_model() in the child process, I got the following errors:

E tensorflow/stream_executor/cuda/cuda_driver.cc:1287] could not retrieve CUDA device count: CUDA_ERROR_NOT_INITIALIZED
F tensorflow/stream_executor/cuda/cuda_driver.cc:312] Check failed: CUDA_SUCCESS == cuCtxSetCurrent(cuda_context->context()) (0 vs. 3)

**Comment by andrewtsuei** [comment]
After removing getting available GPUs with tensorflow.python.client.device_lib in the main process and specifying GPU ids in a config file, it worked.

**Comment by TCherici** [comment]
For people looking for an automated method for finding the number of GPUs available:

The GPUs are "claimed" by the call to `tensorflow.python.client.device_lib`. If this function is called in a child process that is subsequently killed, the GPUs are then available again.

Example function:

```
from tensorflow.python.client import device_lib
from multiprocessing import Process, Queue

def get_available_gpus_child_process(gpus_list_queue):
    local_device_protos = device_lib.list_local_devices()
    gpus_list = [x.name for x in local_device_protos if x.device_type == 'GPU']
    gpus_list_queue.put(gpus_list)


def get_available_gpus():
    gpus_list_queue = Queue()
    proc_get_gpus = Process(target=get_available_gpus_child_process, args=(gpus_list_queue,))
    proc_get_gpus.start()
    proc_get_gpus.join()
    gpus_list = gpus_list_queue.get()
    return gpus_list
```

**Comment by Heronalps** [comment]
I put the GPU number request outside the main function, because I want NUM_GPU to be global. It works fine when the script is called directly in runtime, but having the same problem when the script is a child process called by another parent process. I solved it by moving the request into the main function (handler). 

Sample code follows:

```
def handler(event, context):
   
    # Parallel with multiple GPUs
    available_devices = device_lib.list_local_devices()
    NUM_GPU = len([x for x in available_devices if x.device_type == 'GPU'])

    # Increase BATCH_SIZE based on number of GPUs to harness the quasi-linear speedup of multiple GPUS
    BATCH_SIZE = 8 * NUM_GPU if NUM_GPU > 0 else 8

```
